# Generated by Django 3.0.2 on 2020-03-09 06:33

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdAt', links.models.KinveyDateField(auto_now_add=True)),
                ('updatedAt', links.models.KinveyDateField(auto_now=True)),
            ],
        ),
    ]
